# This file is autogenerated by generate_courses.rb

def course_spaces
    [15, 30, 45, 60].sample
end

upload_images = false

course = Course.new college_id: 1
course.title = 'SPD Marine Engineering (Cadet Training) PDA'
course.category = Category.find_by_name 'Nautical Studies & Marine Engineering'
course.level = 'SCQF level 9'
course.start_date = Date.new 2017, 8, 28
course.end_date = Date.new 2018, 6, 13
if upload_images
  course.image = Rails.root.join('app/assets/images/seed_images2/MarineManagementPDA.jpg').open
else
  course.image.filename = 'MarineManagementPDA.jpg'
end
course.description = "This is a three year training programme aimed at providing the necessary training and qualifications for employment as an Engineering Officer of the Watch. The HND in Marine Engineering will also give academic exemptions for management level exams further in your career path, while the SPD Marine management element will give exemptions from the IAMI Engineering Knowledge examination.\n\nThere are a number of elements to the programme and also a compulsory sea time requirement of seven months.\n\nThe programme is structured into 5 phases:\n\nPhase 1 – College phase where you will complete year 1 of HND in Marine Engineering, compulsory STCW short courses, MCA workshop skills and industrial experience.\n\nPhase 2 – Sea phase where you will start your MNTB training record book in addition to a work based learning course and a distance learning maths course.\n\nPhase 3 – College phase where you will complete year 2 of the HND in Marine Engineering (excluding the graded unit project), STCW short courses, MCA workshop skills and industrial experience.\n\nPhase 4 – Sea phase where you will complete your MNTB training record book.\n\nPhase 5 – College phase where you will complete an SPD in Maritime Management and HND Marine Engineering graded unit 2 projects in addition to preparing for your MCA Oral Examination and completing your final STCW short courses. Additional maths tuition in order to aide transition to university will also be provided.\n\nThere are two main entries into this programme: A September entry and also a January entry.\n\nFor further information see http://www.careersatsea.org/."
course.entry_requirements = "To gain entry to the course you should have any of the following combinations of qualifications:\n\n1. Higher maths and/or physical science at grade C or above, and national 5/GCSE or equivalent which must include:\n* English.\n* Maths.\n* Physical Science (e.g. Physics, Chemistry, Technological Studies or Engineering Science).\n* One other subject.\n\n2. NC Shipping and Maritime Operations (SCQF Level 6) with optional Engineering units.\n\n3. Alternative qualifications will be considered on an individual basis in conjunction with the sponsoring company or training provider.\n\nStudents must have a sponsoring company in order to fulfil the sea time requirement of this programme.\n\nInitial applications for this course should be submitted to a training provider or company, please follow the link for more information."
course.career_prospects = "On successful completion of the SPD programme, cadets can gain employment as a fully qualified officer of the watch or choose to progress into university to study at a higher level."
course.spaces = course_spaces
course.status = :cancelled
puts 'SPD Marine Engineering (Cadet Training) PDA uploaded!' if upload_images
course.save! validate: false

course = Course.new college_id: 1
course.title = 'Business HNC'
course.category = Category.find_by_name 'Business & Procurement'
course.level = 'SCQF level 7'
course.start_date = Date.new 2017, 8, 28
course.end_date = Date.new 2018, 6, 13
if upload_images
  course.image = Rails.root.join('app/assets/images/seed_images2/Business_HNC.jpg').open
else
  course.image.filename = 'Business_HNC.jpg'
end
course.description = "Are you looking for a career in banking, insurance, civil service, local government or distribution? This course gives you the skills and knowledge necessary to succeed, with excellent career opportunities and progression routes. \n\nYou'll be taught by staff with relevant industry experience and a proven track record of bringing out the best in their students.\n\nToday, the internet is an important part of business, so we've updated the course to include analysing and using information for strategic purposes.\n\nThis course is placed on the Scottish Credit Qualifications Framework at Level 7. For more information on the framework visit: www.scqf.org.uk/the-framework/."
course.entry_requirements = "* One Higher pass in a relevant* academic subject OR\n* National Certificate in Business (with at least 3 units at level 6) OR\n* Other appropriate and relevant National Certificate courses (with at least 3 units at level 6) may be considered.\n* Relevant Work experience may be considered.\n* relevant academic subjects include English, Administration, Business Management, Economics, Geography, History, Mathematics, Modern Studies or a Science subject.\n\nYou'll be invited to attend a group presentation and interview session.  The presentation will give you all of the information you need about the course, this will be followed on the same day by an individual interview where you can tell us why you're interested in this course and ask any specific questions related to your own application."
course.career_prospects = "You could expect to apply for a trainee management position and/or a team leader in industry or commerce."
course.spaces = course_spaces
course.status = :open
puts 'Business HNC uploaded!' if upload_images
course.save! validate: false

course = Course.new college_id: 2
course.title = 'Administration and Information Technology  HND'
course.category = Category.find_by_name 'Administration, Human Resources & Law'
course.level = 'SCQF level 8'
course.start_date = Date.new 2017, 8, 28
course.end_date = Date.new 2019, 6, 13
if upload_images
  course.image = Rails.root.join('app/assets/images/seed_images2/Business_boys_learning.jpg').open
else
  course.image.filename = 'Business_boys_learning.jpg'
end
course.description = "This course will provide you with a broad range of office-based skills and knowledge required for a career in office administration. This is a challenging course, where you'll develop specialist skills in IT, desktop publishing, communication, research and planning.\n\nYour stimulating programme will be delivered by our highly professional teaching staff with significant experience in office administration and a proven track record of bringing out the best in their students.\n\nThis course accepts year two direct entrants (you must have a completed HNC Administration, please see further information in direct entry section)\n\nThis course is placed on the Scottish Credit Qualifications Framework at Level 7 (year 1) and Level 8 (year 2).  For more information on the framework visit: www.scqf.org.uk/the-framework/."
course.entry_requirements = "* Two Highers in a relevant* academic subject OR\n* Relevant Work experience may be considered.\n* relevant academic subjects include English, Administration, Business Management, Economics, Geography, History, Mathematics, Modern Studies or a Science subject.\n\nYou'll be invited to attend a group presentation and interview session.  The presentation will give you all of the information you need about the course, this will be followed on the same day by an individual interview where you can tell us why you are interested in this course and ask any specific questions related to your own application."
course.career_prospects = "This course prepares you for a career as a Personal Assistant or Administrator in both the public and private sector. The HND can provide progression into employment in a general administrative role within small to medium enterprises. It'll also provide opportunities to develop the skills and knowledge required for more specialist posts demanded by larger organisations.\n\nThe qualification will allow you to develop:\n\n* Technical and administrative knowledge relevant to current practice.\n* Interpersonal skills relevant to an administrative role.\n* Personal effectiveness.\n* Communication.\n* Presentation technique."
course.spaces = course_spaces
course.status = :cancelled
puts 'Administration and Information Technology  HND uploaded!' if upload_images
course.save! validate: false

course = Course.new college_id: 3
course.title = 'Information Technology HNC'
course.category = Category.find_by_name 'Applied Computing & Digital Technologies'
course.level = 'SCQF level 7'
course.start_date = Date.new 2017, 8, 28
course.end_date = Date.new 2019, 6, 13
if upload_images
  course.image = Rails.root.join('app/assets/images/seed_images2/InformationTechnology_HNC.jpg').open
else
  course.image.filename = 'InformationTechnology_HNC.jpg'
end
course.description = "This computing course provides the entry level knowledge and IT skills you need to work in computing. The course will provide you with an opportunity to undertake a variety of practical and theoretical activities and assessments, which will prepare you for higher learning, or entry into the job market.\n\nIf you successfully complete the course, you can apply for entry to the second year HND program where you'll have the opportunity to further enhance your knowledge and skills by building e-commerce applications using the Microsoft.Net framework and undertaking the Industry recognised Oracle Database Design and Programming vendor qualification.\n\nThis course is placed on the Scottish Credit Qualifications Framework at Level 7. For more information on the framework visit: www.scqf.org.uk/the-framework/."
course.entry_requirements = "* One appropriate Higher and three Intermediate 2 courses (including at least one from Computing or Information Systems); OR\n* One Higher and three Standard Grades at Credit level; OR\n* One Higher and three National 5 qualifications; OR\n* A national qualification at SCQF Level 5/6 in a related subject (such as Digital Media Computing, Computing: Technical Support or Software Development); OR\n* Other equivalent qualifications or experience.\nYou'll be invited for a group and/or individual interview where you can find out more about the course and tell us why you are interested in this subject."
course.career_prospects = "The course will develop your core and employability skills and make you more attractive to prospective employers."
course.spaces = course_spaces
course.status = :open
puts 'Information Technology HNC uploaded!' if upload_images
course.save! validate: false

course = Course.new college_id: 3
course.title = 'Information Technology HND'
course.category = Category.find_by_name 'Applied Computing & Digital Technologies'
course.level = 'SCQF level 8'
course.start_date = Date.new 2017, 8, 28
course.end_date = Date.new 2019, 6, 13
if upload_images
  course.image = Rails.root.join('app/assets/images/seed_images2/Computing_Hard_drive_0.jpg').open
else
  course.image.filename = 'Computing_Hard_drive_0.jpg'
end
course.description = "The HND Information Technology computing qualification is designed to give you a solid technical understanding of information systems and technologies used by both small and large scale businesses.\n\nYou'll gain an understanding of how data is transformed into usable information through the theory and practice of relational database technologies. You'll also undertake units in web design and development, e-commerce, applications programming, operating systems and project management.\n\nAs part of the second year program you'll also undertake the Oracle Database Design and Programming using SQL vendor qualification, which is a worldwide recognised qualification that prepares the student to undertake external Oracle exams.\n\nThis course is placed on the Scottish Credit Qualifications Framework at Level 8. For more information on the framework visit: www.scqf.org.uk/the-framework/."
course.entry_requirements = "* Two Highers and three Intermediate 2 courses (including Computing or Information Systems); OR\n* Two Higher and three Standard Grades at Credit level (including Computing or Information Systems); OR\n* Two Higher and three National 5 level qualifications (including Computing or Information Systems); OR\n* A national qualification at SCQF Level 6 in a related subject such as Digital Media Computing, NQ Computing.\nYou'll be invited for a group and/or individual interview where you can find out more about the course and tell us why you're interested in this subject."
course.career_prospects = "After completing the HND you may pursue a career in business intelligence analysis, information management, database administration, trainer/teacher, hardware and software support, or web development."
course.spaces = course_spaces
course.status = :open
puts 'Information Technology HND uploaded!' if upload_images
course.save! validate: false

course = Course.new college_id: 2
course.title = 'Web Development HND'
course.category = Category.find_by_name 'Applied Computing & Digital Technologies'
course.level = 'SCQF level 8'
course.start_date = Date.new 2017, 8, 28
course.end_date = Date.new 2019, 6, 13
if upload_images
  course.image = Rails.root.join('app/assets/images/seed_images2/WebDevelopent_HND.jpg').open
else
  course.image.filename = 'WebDevelopent_HND.jpg'
end
course.description = "On this two year course, you'll gain skills to start or advance a career as a web designer/developer. You'll learn to build both static and dynamic websites that deliver content in a variety of formats for computers, smartphones and tablets. You'll have access to current smartphones and tablets for testing your responsive websites."
course.entry_requirements = "* Two Higher and three Intermediate 2 courses (including Computing, Graphic Design or Information Systems); OR\n* Two Higher and three Standard Grades at Credit level or above (including Computing, Graphic Design or Information Systems); OR\n* Two Higher and three National 5 qualifications or above (including Computing, Graphic Design or Information Systems); OR\n* A national qualification at SCQF Level 5 or 6 in a related subject such as Digital Media Computing, NQ Computing,  Computing: Technical Support or Software Development.\nYou'll be invited for a group and/or individual interview where you will get the opportunity to find out more about the course and tell us why you're interested in this subject area. It is important that you prepare a personal statement which reflects your desire to study on this course."
course.career_prospects = "Apply for various job vacancies, such as a junior web developer/designer.\n\nContinuining Study\n\nYou'll have the opportunity to progress to the following degree courses at university:\n\n* BSc (Hons) Web and Mobile Development at the University of the West of Scotland.\n* BSc/BSc (Hons) Interactive Media Design at Napier University.\n* BSc/BSc (Hons) Digital Media at Napier University.\n* BSc/BSc (Hons) Creative Computing at Napier University.\n* BEng (Hons) Web Technologies at Napier University."
course.spaces = course_spaces
course.status = :open
puts 'Web Development HND uploaded!' if upload_images
course.save! validate: false
