# Postgresql Database Config

production:
  adapter: postgresql
  encoding: unicode
  database: futureprospects_production
  pool: 5
  username: alex
  password: admin
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: futureprospects
  pool: 5
  username: alex
  password: admin
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: futureprospects_test
  pool: 5
  username: alex
  password: admin
  host: localhost

