# Postgresql Database Config

development:
  adapter: postgresql
  encoding: unicode
  database: futureprospects
  pool: 5
  username: alexm
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: futureprospects_test
  pool: 5
  username: alexm
  password: admin

