# These are handled by Figaro

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
