# These are handled by Figaro

default:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  braintree_merchant_id: <%= ENV["BRAINTREE_MERCHANT_ID"] %>
  braintree_public_key: <%= ENV["BRAINTREE_PUBLIC_KEY"] %>
  braintree_private_key: <%= ENV["BRAINTREE_PRIVATE_KEY"] %>
  paypal_username: <%= ENV["PAYPAL_USERNAME"] %>
  paypal_password: <%= ENV["PAYPAL_PASSWORD"] %>
  paypal_signature: <%= ENV["PAYPAL_SIGNATURE"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  