# * Name: Alex McBride
# * Date: 25/05/2017
# * Project: Future Prospects
# * Model class to represent a staff member's role. This class is autmatically generated by Rolify.
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  # @!attribute resource
  #   @return [Object]
  #   A resource attached to this role.
  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end
